# Generated by Django 5.1.1 on 2024-09-28 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Axis',
            fields=[
                ('axis_id', models.AutoField(primary_key=True, serialize=False)),
                ('axis_name', models.CharField(choices=[('X', 'X'), ('Y', 'Y'), ('Z', 'Z'), ('A', 'A'), ('C', 'C')], max_length=1)),
                ('max_acceleration', models.DecimalField(decimal_places=3, max_digits=10)),
                ('max_velocity', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_name', models.CharField(max_length=255)),
                ('tool_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AxisData',
            fields=[
                ('axis_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('actual_position', models.DecimalField(decimal_places=3, max_digits=10)),
                ('target_position', models.DecimalField(decimal_places=3, max_digits=10)),
                ('distance_to_go', models.DecimalField(decimal_places=3, editable=False, max_digits=10)),
                ('homed', models.BooleanField()),
                ('acceleration', models.DecimalField(decimal_places=3, max_digits=10)),
                ('velocity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('update_timestamp', models.DateTimeField(auto_now_add=True)),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axis_data', to='user_management.axis')),
            ],
        ),
        migrations.AddField(
            model_name='axis',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axes', to='user_management.machine'),
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('tool_id', models.AutoField(primary_key=True, serialize=False)),
                ('tool_offset', models.FloatField()),
                ('feedrate', models.FloatField()),
                ('update_timestamp', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='user_management.machine')),
            ],
        ),
        migrations.CreateModel(
            name='ToolUsage',
            fields=[
                ('usage_id', models.AutoField(primary_key=True, serialize=False)),
                ('tool_in_use', models.IntegerField()),
                ('update_timestamp', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_usages', to='user_management.machine')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='axis',
            unique_together={('machine', 'axis_name')},
        ),
    ]
