# Generated by Django 5.1.1 on 2024-09-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='axis',
            table='axis',
        ),
        migrations.AlterModelTable(
            name='axisdata',
            table='axis_data',
        ),
        migrations.AlterModelTable(
            name='machine',
            table='machine',
        ),
        migrations.AlterModelTable(
            name='tool',
            table='tool',
        ),
        migrations.AlterModelTable(
            name='toolusage',
            table='tool_usage',
        ),
    ]
